// Collection: Categories
// Description: Budget categories created by each user

// Fields:
// _id           ObjectId  - auto generated by MongoDB
// userId        ObjectId  - references Users._id
// name          string    - category name (e.g. "Food", "Rent")
// budgetLimit   number    - max budget amount
// budgetSpent   number    - amount spent so far (updated on transactions)
// budgetPeriod  string    - "weekly", "monthly", or "yearly"

// Example document:
// {
//   _id: ObjectId("..."),
//   userId: ObjectId("..."),
//   name: "Food",
//   budgetLimit: 500,
//   budgetSpent: 120,
//   budgetPeriod: "monthly"
// }