// Collection: Transactions
// Description: Individual spending transactions logged by users

// Fields:
// _id         ObjectId  - auto generated by MongoDB
// userId      ObjectId  - references Users._id
// categoryId  ObjectId  - references Categories._id
// amount      number    - transaction amount
// date        date      - date of transaction
// note        string    - optional note (e.g. "Grocery run")

// Example document:
// {
//   _id: ObjectId("..."),
//   userId: ObjectId("..."),
//   categoryId: ObjectId("..."),
//   amount: 45.50,
//   date: ISODate("2026-03-27"),
//   note: "Walmart groceries"
// }