// Collection: Users
// Description: Stores registered user accounts

// Fields:
// _id         ObjectId  - auto generated by MongoDB
// username    string    - unique username
// password    string    - plain text password (hash later if needed)

// Example document:
// {
//   _id: ObjectId("..."),
//   username: "john123",
//   password: "mypassword"
// }